image: debian:latest

stages:
    - build_and_test

build_script:
    stage: build_and_test
    script:
        - apt-get -y update
        - apt-get -y install automake
        - apt-get -y install make
        - apt-get -y install texinfo
        - apt-get -y install openjdk-8-jdk
        - apt-get -y install gcc
        - ./autogen.sh
        - ./configure
        - make
        - make check