;; Kawa-options: "-f" %F

(define (foo a ::array) (a 0))
(format #t "foo ~w~%" (foo #(a b c)))
;; Output: foo a

(define (foo1 a ::array1) (a 0))
(format #t "foo1 ~w~%" (foo1 #(a b c)))
;; Output: foo1 a

(display (build-array #2a((1 11)
                          (1 11))
                      vector->list))
(newline)
;; Output: #2a@1:10@1:10(((1 1)                (1 2)                (1 3)               
;; Output:               (1 4)                (1 5)                (1 6)               
;; Output:               (1 7)                (1 8)                (1 9)               
;; Output:               (1 10)               )
;; Output:              ((2 1)                (2 2)                (2 3)               
;; Output:               (2 4)                (2 5)                (2 6)               
;; Output:               (2 7)                (2 8)                (2 9)               
;; Output:               (2 10)               )
;; Output:              ((3 1)                (3 2)                (3 3)               
;; Output:               (3 4)                (3 5)                (3 6)               
;; Output:               (3 7)                (3 8)                (3 9)               
;; Output:               (3 10)               )
;; Output:              ((4 1)                (4 2)                (4 3)               
;; Output:               (4 4)                (4 5)                (4 6)               
;; Output:               (4 7)                (4 8)                (4 9)               
;; Output:               (4 10)               )
;; Output:              ((5 1)                (5 2)                (5 3)               
;; Output:               (5 4)                (5 5)                (5 6)               
;; Output:               (5 7)                (5 8)                (5 9)               
;; Output:               (5 10)               )
;; Output:              ((6 1)                (6 2)                (6 3)               
;; Output:               (6 4)                (6 5)                (6 6)               
;; Output:               (6 7)                (6 8)                (6 9)               
;; Output:               (6 10)               )
;; Output:              ((7 1)                (7 2)                (7 3)               
;; Output:               (7 4)                (7 5)                (7 6)               
;; Output:               (7 7)                (7 8)                (7 9)               
;; Output:               (7 10)               )
;; Output:              ((8 1)                (8 2)                (8 3)               
;; Output:               (8 4)                (8 5)                (8 6)               
;; Output:               (8 7)                (8 8)                (8 9)               
;; Output:               (8 10)               )
;; Output:              ((9 1)                (9 2)                (9 3)               
;; Output:               (9 4)                (9 5)                (9 6)               
;; Output:               (9 7)                (9 8)                (9 9)               
;; Output:               (9 10)               )
;; Output:              ((10 1)                (10 2)                (10 3)               
;; Output:               (10 4)                (10 5)                (10 6)               
;; Output:               (10 7)                (10 8)                (10 9)               
;; Output:               (10 10)               ))
